Update workflows and helm resources (#25)
* Update action to login to registry

* Update terraform resources

* Update npm packages

* Improve workflows

* Turn off audit for tests purposes

* Revert "Turn off audit for tests purposes"

This reverts commit 20bc15f3b76fcb8269e725ca57356898f4593d1b.

* Turn off audit again

* Update workflow to allow rebuild

* Fix syntax

* Revert "Turn off audit again"

This reverts commit c988ca4d1b13aa0507ab9258d7523f50efcf436b.

* Update helm configs

* Update image in dev

* Update helm values

* Update helm chart resources

* Update kubernetes infra resources

* Update terraform lock

* Update certificate in helm values

* Update destinationrule template

* Fix issues with istio objects

* Add blank line at end of file

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -28,7 +28,19 @@ jobs:
       - name: Create image tag
         id: customvars
         run: |
-          echo "image_tag=${GITHUB_REF_NAME//\//_}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          #!/usr/bin/env bash
+
+          set -euo pipefail
+
+          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
+              echo 'This is build from tag.'
+              echo "image_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
+          elif [[ "$GITHUB_REF" == refs/heads/* ]]; then
+              echo 'This is build from branch.'
+              echo "image_tag=${GITHUB_REF_NAME//\//_}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          else
+              echo 'Unknown ref type, failing build!'
+          fi
 
       - name: Get app version from package.json
         uses: sergeysova/jq-action@v2
@@ -80,10 +92,10 @@ jobs:
           /tmp/nodejs-colorizedapp_${{ needs.call-security-scans-container-workflow.outputs.image_tag }}.tar
 
       - name: Login to Azure Container Registry
-        uses: azure/docker-login@v1
+        uses: docker/login-action@v3
         with:
           # Global variable in GH
-          login-server: ${{ vars.ACR_ADDRESS }}
+          registry: ${{ vars.ACR_ADDRESS }}
           # Secrets in GH
           username: ${{ secrets.ACR_LOGIN }}
           password: ${{ secrets.ACR_PASS }}
diff --git a/.github/workflows/psa.yaml b/.github/workflows/psa.yaml
--- a/.github/workflows/psa.yaml
+++ b/.github/workflows/psa.yaml
@@ -83,10 +83,10 @@ jobs:
           category: SAST
 
       - name: Login to Azure Container Registry
-        uses: azure/docker-login@v1
+        uses: docker/login-action@v3
         with:
           # Global variable in GH
-          login-server: ${{ vars.ACR_ADDRESS }}
+          registry: ${{ vars.ACR_ADDRESS }}
           # Secrets in GH
           username: ${{ secrets.ACR_LOGIN }}
           password: ${{ secrets.ACR_PASS }}
@@ -137,6 +137,10 @@ jobs:
             exit 1
           fi
           echo 'Checking SCA (Docker) sarif report against critical severities...'
+          if [[ ! -f trivy-results.sarif ]]; then
+            echo 'File trivy-results.sarif not found, failing build!'
+            exit 1
+          fi
           if grep 'Severity: critical' 'trivy-results.sarif' -ivqz; then
             echo 'No vulnerabilities with severity critical found'
           else
