Workaround for bearer issues

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -100,22 +100,24 @@ jobs:
           github.event_name == 'workflow_dispatch'
         uses: bearer/bearer-action@v2
         continue-on-error: true
+        id: sast
         with:
           format: sarif
           output: bearer-results.sarif
 
-      - name: Debug
-        run: cat bearer-results.sarif
-
+      # Bearer produces empty report if no issues were found
+      # and it can't be processed; upload report only if 
+      # exit code == 1
       - name: Upload SAST scan results to GitHub Security tab
-        if: (contains(github.event.comment.body, '/rerun') &&
-          github.event_name == 'issue_comment') ||
-          github.event_name == 'pull_request' ||
-          github.event_name == 'workflow_dispatch'
+        if: ${{ steps.sast.outputs.exit_code == 1 }}
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: bearer-results.sarif
           category: SAST
+
+      - name: Fail workflow if SAST scan failed
+        if: ${{ steps.sast.outputs.exit_code == 1 }}
+        run: exit 1
 
       - name: Run unit tests
         uses: actions/setup-node@v3
@@ -129,8 +131,7 @@ jobs:
         uses: actions/github-script@v7
         if: (contains(github.event.comment.body, '/rerun') &&
           github.event_name == 'issue_comment') ||
-          github.event_name == 'pull_request' ||
-          github.event_name == 'workflow_dispatch'
+          github.event_name == 'pull_request'
         with:
           script: |
             const name = '${{ github.workflow }}';
